export const FoodCaloriesData = {
  green_olive: {
    calories: 4,
    weight: 3,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/green_olive.png"),
  },
  fig: {
    calories: 30,
    weight: 46,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/fig.png"),
  },
  mangosteen: {
    calories: 61,
    weight: 80,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/mangosteen.png"),
  },
  apple: {
    calories: 89,
    weight: 140,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/apple.png"),
  },
  dragon_fruit: {
    calories: 119,
    weight: 198,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/dragon_fruit.png"),
  },
  black_bean: {
    calories: 149,
    weight: 40,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/black_bean.png"),
  },
  grape: {
    calories: 169,
    weight: 125,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/grape.png"),
  },
  mango: {
    calories: 215,
    weight: 350,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/mango.png"),
  },
  yogurt: {
    calories: 241,
    weight: 227,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/yogurt.png"),
  },
  chocolate_milk: {
    calories: 264,
    weight: 350,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/chocolate_milk.png"),
  },
  croissant: {
    calories: 294,
    weight: 57,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/croissant.png"),
  },
  egg_mcmuffin: {
    calories: 322,
    weight: 126,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/egg_mcmuffin.png"),
  },
  apple_crumble: {
    calories: 360,
    weight: 114,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/apple_crumble.png"),
  },
  cheese_pizza: {
    calories: 379,
    weight: 125,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/cheese_pizza.png"),
  },
  chicken_curry: {
    calories: 412,
    weight: 450,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/chicken_curry.png"),
  },
  large_french_fries: {
    calories: 434,
    weight: 150,
    portion: "1 portion",
    image: require("../../assets/pedometer-analysis/large_french_fries.png"),
  },
  egg_sandwich: {
    calories: 474,
    weight: 159,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/egg_sandwich.png"),
  },
  chili_hotdog: {
    calories: 520,
    weight: 200,
    portion: "1 piece",
    image: require("../../assets/pedometer-analysis/chili_hotdog.png"),
  },
};
